version: '3.4'

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    networks: # Deine network (defaut is bridge)
      - main
    ports:
      - "6379:6379"

  app:
    build:
      context: ../demo2/flask_api/ # define build path
      dockerfile: Dockerfile # name of the dockerfile
    image: flask_service
    container_name: flask_app
    depends_on: # define dependencies among services
      - redis
      - celery_service
    ports:
      - "4001:5001"
    hostname: app # specify hostname
    networks:
      - main
    volumes:
      - flask_app_volume:/var/local/ # User defined volumes
    restart: on-failure # restart policy

  celery_service:
    build:
      context: ../demo2/taskqueue/
      dockerfile: Dockerfile
    image: celery_service
    volumes:
      - celery_app_volume:/var/local/
    container_name: celery_app
    depends_on:
      - redis
    hostname: celery
    networks:
      - main

networks:
  main:

volumes:
  flask_app_volume:
  celery_app_volume:

# reference documentation  - https://docs.docker.com/compose/compose-file/